### ISSUE TITLE
An error when run your codes

### ISSUE THREAD

**Issue by Spatial-R** [mbjoseph/knitr-template#1]
When i copy your codes and run in my compute, the error was in the following codes:

``` r results="asis", echo=FALSE
bibliography(style="markdown")
```

The error shows that the cat cannot handle with list.  The version of knitcitations was 1.0.7.

**Comment by mbjoseph** [comment]
Thanks! This should be fixed now after switching from the dev version of knitcitations to the version available via CRAN with this commit f7b2e1e6cac12c8bc83333a10f79599fcbe14390
